filebeat.inputs:
# Semaphore logs
- type: filestream
  id: semaphore-logs
  paths:
    - /var/log/semaphore/*.log
  fields:
    log_type: semaphore
    service: semaphore-ui
  fields_under_root: true

# Docker container logs
- type: docker
  containers.ids:
    - "*"
  fields:
    log_type: docker
  fields_under_root: true

# VM system logs (will be configured by Ansible on target VMs)
- type: filestream
  id: vm-system-logs
  enabled: false
  paths:
    - /var/log/syslog
    - /var/log/auth.log
    - /var/log/kern.log
  fields:
    log_type: vm-system
  fields_under_root: true

# VM application logs
- type: filestream
  id: vm-application-logs
  enabled: false
  paths:
    - /var/log/applications/*.log
  fields:
    log_type: vm-application
  fields_under_root: true

processors:
- add_host_metadata:
    when.not.contains.tags: forwarded
- add_docker_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
